server:
  port: 8642

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka
feign:
  hystrix:
    enabled: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            add:
              type:
                headers: false

notification:
  changepass:
    eventid: 2
    scheduled: false
  forgetpass:
    eventid: 1
    scheduled: false 
ui_url: https://app.gamifylearningcentre.com/app
service_url: https://app.gamifylearningcentre.com/api/password-service/

---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://10.0.2.204:5432/user_management
    username: postgres
    password: secretPass

eureka:
  instance:
    ip-address: 10.0.2.81
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
ui_url: https://beta.gamifylearningcentre.com/app
service_url: https://beta.gamifylearningcentre.com/api/password-service/
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://10.0.1.63:5432/user_management
    username: user_management
    password: usrmgmt

eureka:
  instance:
    ip-address: 10.0.1.108
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
ui_url: https://app.gamifylearningcentre.com/app
service_url: https://app.gamifylearningcentre.com/api/password-service/
