eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka
    fetchRegistry: true
  instance: 
    ip-address: localhost
    preferIpAddress: true
server:
  port: 8999
feign:
  hystrix:
    enabled: true
spring:
  http:
    multipart:
      max-file-size: 500000KB
      max-request-size: 500000KB
  datasource: 
    url: jdbc:postgresql://localhost:5432/user_management
    username: user_management
    password: usrmgmt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
multipart:
  enabled: true
ui_url: http://localhost:3000/app
---
spring:
  profiles: staging
  datasource: 
    url: jdbc:postgresql://10.0.2.204:5432/user_management
    username: postgres
    password: secretPass
eureka:  
  instance: 
    ip-address: 10.0.2.81
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
ui_url: http://18.215.53.195/app
---
spring:
  profiles: performance
  datasource: 
    url: jdbc:postgresql://10.0.1.159:5432/user_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  instance: 
    ip-address: 10.0.1.8
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
ui_url: http://18.210.136.97/app
---
spring:
  profiles: production
  datasource: 
    url: jdbc:postgresql://10.0.1.63:5432/user_management
    username: user_management
    password: usrmgmt
eureka:
  instance: 
    ip-address: 10.0.2.108
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
ui_url: http://18.210.136.97/app
